spring.application.name=JAVA_Seminar5_2026


#MySQL konfiguracija lokalajam MySQL serverim
spring.jpa.hibernate.ddl-auto=create-drop
spring.datasource.url=jdbc:mysql://${MYSQL_HOST:localhost}:3306/minirimi
spring.datasource.username=userspring
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name =com.mysql.jdbc.Driver

#MySQL konfiguracija VeA MySQL serverim
#spring.jpa.hibernate.ddl-auto=create-drop
#spring.datasource.url=jdbc:mysql://10.0.6.178:3306/KarinaSkirmantedb
#spring.datasource.username=KarinaSkirmante
#spring.datasource.password=${DB_PASSWORD}
#spring.datasource.driver-class-name =com.mysql.jdbc.Driver



# H2 konfiguracija
#spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=userspring
#spring.datasource.password=${DB_PASSWORD}
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#spring.h2.console.enabled=true